// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IArticleFields {
  /** Title */
  title: string;

  /** Author */
  author: IAuthor;

  /** Date Published */
  datePublished: string;

  /** Excerpt */
  excerpt: string;

  /** Keywords */
  keywords: string[];

  /** Featured Image */
  featuredImage: Asset;

  /** Body */
  body: string;

  /** Body 2 */
  body2?: string | undefined;

  /** slug */
  slug: string;
}

export interface IArticle extends Entry<IArticleFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "article";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IAuthorFields {
  /** Name */
  name: string;

  /** Job Title / Role */
  role?: string | undefined;

  /** Location */
  location: string;

  /** Short Description */
  shortDescription?: string | undefined;

  /** Bio */
  bio: string;

  /** Twitter */
  twitter: string;

  /** Instagram */
  instagram: string;

  /** LinkedIn */
  linkedin: string;

  /** Github */
  github?: string | undefined;

  /** Headshot */
  headshot: Asset;
}

export interface IAuthor extends Entry<IAuthorFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "author";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IProjectFields {
  /** Title */
  title: string;

  /** slug */
  slug: string;

  /** Keywords / Tags */
  keywords: string[];

  /** Featured Image */
  featuredImage: Asset;

  /** Excerpt */
  excerpt: string;

  /** Body */
  body: string;

  /** Body 2 */
  body2?: string | undefined;
}

export interface IProject extends Entry<IProjectFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "project";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "article" | "author" | "project";

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
